apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks3
  region: us-east-1

vpc:
  id: "vpc-e5e6449f"
  cidr: "172.31.0.0/16"
  subnets:
    private:
      us-east-1a:
          id: "subnet-08ee1667ebe5b0c98"
          cidr: "172.31.0.0/25"
      us-east-1c:
          id: "subnet-0b01f8fea5059cc57"
          cidr: "172.31.0.128/25"
    public:
      us-east-1b:
          id: "subnet-045cfd31d5ae8fd1e"
          cidr: "172.31.1.0/25"
      us-east-1d:
          id: "subnet-030353b93efc35163"
          cidr: "172.31.1.128/25"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true

iam:
  serviceRoleARN: "arn:aws:iam::205172468134:role/eks-role"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
