apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: apptest
spec:
  selector:
    matchLabels:
      app: apptest
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: apptest
    spec:
      containers:
      - name: apptest
        image: 205172468134.dkr.ecr.us-east-1.amazonaws.com/eks-test:latest
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
