---
apiVersion: v1
kind: Service
metadata:
  name: apptest
  #  annotations:
  #  service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: apptest
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
   # protocol: TCP
  selector:
    app: apptest
